[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['echo "Build completed - using simple deployment"']

[start]
cmd = 'node app.cjs'

[variables]
NODE_ENV = 'production'