[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm ci',
  'npm run build'
]

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'NODE_ENV=production tsx server/index.ts'

[variables]
NODE_ENV = 'production'