name: gg deployment

on:
  push:
    branches:
      - main  # หรือเปลี่ยนชื่อ branch ตามที่ใช้จริง

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SCP
        env:
          SSH_USER: <your-username>
          SSH_HOST: <your-server-ip>
          DEPLOY_PATH: <your-server-path>
        run: |
          scp -o StrictHostKeyChecking=no -r ./<your-app-directory>/* $SSH_USER@$SSH_HOST:$DEPLOY_PATH
